from setuptools import setup

setup(name="scidataspace-sciunit-client",
      version="0.1a1",
      description="SciDataspace Client for creating sciunits",
      long_description=open("README.rst").read(),
      author="Cristian Vlaescu, Tanu Malik",
      author_email="tanum@ci.uchicago.edu",
      url="https://github.com/globusonline/catalog-client",
      install_requires=['leveldb>=0.193','configparser'],
      packages=["scidataspace",
                "scidataspace.client",
                "scidataspace.client.members",
                "scidataspace.client.members.tagfilerutil",
                "scidataspace.client.globusonline",
                "scidataspace.client.globusonline.catalog",
                "scidataspace.client.globusonline.catalog.client",
                "scidataspace.client.globusonline.catalog.client.ca",
                "scidataspace.client.globusonline.catalog.client.examples"],
      package_data={
      		"scidataspace.client":[".gdclient/*"],
      		"scidataspace.client.globusonline.catalog.client": ["ca/*.pem"] },
      scripts=["scidataspace/client/gdclient.py"], #globusonline/catalog/client/cli/catalog.py"],
      keywords=["scidataspace","globusonline"],
      classifiers=[
          "Development Status :: 3 - Alpha",
          "Intended Audience :: Users",
          "License :: OSI Approved :: Apache Software License",
          "Operating System :: MacOS :: MacOS X",
          "Operating System :: Microsoft :: Windows",
          "Operating System :: POSIX",
          "Programming Language :: Python",
          "Topic :: Communications :: File Sharing",
          "Topic :: Internet :: WWW/HTTP",
          "Topic :: Software Development :: Libraries :: Python Modules",
          ],
      )
